### ISSUE TITLE
Layer used for feature extractor using inception model

### ISSUE THREAD

**Issue by dakshvar22** [prith189/Yelp_Restaurant_Photo_Classification#1]
Hi,

May I know which layer have you used for extracting the features for each image. The last but one layer in the pretrained googlenet model for **caffe** returns a 1024 dimensional vector, while your code says it is a 2048 dimensional vector. Specifically, the layer name of the last but one layer is - 'pool5/7x7_s1'.

Any help would be appreciated.

Thanks

**Comment by prith189** [comment]
Hi, I used the MXNET pretrained Inception network from here: https://github.com/dmlc/mxnet-model-gallery/blob/master/imagenet-1k-inception-v3.md , not the one from caffe. 

The layer 'flatten_output' is 2048 dimenisonal.

Thanks,
Prithvi

**Comment by dakshvar22** [comment]
The given URL for downloading the model seems to be down. It does not return any data.
